"""Pydantic schemas for LLM structured outputs.

These schemas define the expected structure of LLM responses
when using structured output mode.
"""

from pydantic import BaseModel, Field


class ArgumentOutput(BaseModel):
    """Single argument generated by the LLM."""

    content: str = Field(description="The argument text")
    qa_indices: list[int] = Field(
        description="Indices of Q&A pairs used to support this argument"
    )


class ArgumentsOutput(BaseModel):
    """Multiple arguments generated by the LLM."""

    arguments: list[ArgumentOutput]


class CriterionScore(BaseModel):
    """Score for a single evaluation criterion."""

    score: int
    reasoning: str


class SingleArgumentScore(BaseModel):
    """All 14 criterion scores for evaluating an argument."""

    scores: list[CriterionScore]


class ArgumentCritique(BaseModel):
    """Devil's advocate critique of an argument."""

    critique: str


class IndividualRefinedArgumentOutput(BaseModel):
    """Refined argument after incorporating feedback."""

    content: str = Field(description="The refined argument text (one paragraph)")
    qa_indices: list[int] = Field(
        description="Indices of Q&A pairs used to support this argument"
    )


class ExecutiveSummaryOutput(BaseModel):
    """LLM output for executive summary: dimension summaries, key points, red flags."""

    strategy_fit_summary: str = Field(description="1-2 sentence summary of strategy fit")
    team_summary: str = Field(description="1-2 sentence summary of team quality")
    potential_summary: str = Field(description="1-2 sentence summary of upside/potential")
    key_points: list[str] = Field(description="4-6 core product/market strengths and differentiators")
    red_flags: list[str] = Field(description="1-5 critical risks or deal-breakers")


class DimensionScoreOutput(BaseModel):
    """LLM output for a single ranking dimension (strategy_fit, team, upside)."""

    raw_score: float = Field(ge=0, le=100, description="Score 0-100")
    confidence: float = Field(ge=0, le=1, description="Evidence confidence 0-1")
    evidence_count: int = Field(ge=0, description="Number of Q&A pairs that contributed")
    evidence_snippets: list[str] = Field(
        default_factory=list,
        description="2-3 short supporting quotes",
    )
    critical_gaps: list[str] = Field(
        default_factory=list,
        description="Missing high-impact facts",
    )
